arm64/dts: fix VtsFirmwareDtboVerification error
VtsFirmwareDtboVerification test failed due to below error:
ERROR: ufdt_verify_fragment():failed to verify fragment[fragment@26],
overlay node __overlay__ to target firmware
Remove firmware node since it's obselete on Q

Change-Id: I03b3e3fe9a5b847601e0829e8cd9b157fb9505c5
Reviewed-on: https://gerrit.mot.com/1470195
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key